### ISSUE TITLE
What is the payload limit?

### ISSUE THREAD

**Issue by Zonalds** [poundifdef/smoothmq#10]
Does SmoothMQ has the same payload limitation as SQS?

**Comment by poundifdef** [comment]
No limit. Send as much data as you want :)

**Comment by poundifdef** [comment]
This is now configurable via `--max-request-size` or `Q_SQS_MAX_REQUEST_SIZE` env var. https://github.com/poundifdef/smoothmq/commit/a6bdba4eba2f40cb863e0193764d38430d6d57b7
