### ISSUE TITLE
Fly

### ISSUE THREAD

**Issue by gedw99** [poundifdef/smoothmq#12]
This would really work well on fly.io ?

There are 2 options to scaling out SQLite...

1. LifeFS

https://fly.io/docs/litefs/speedrun/

3. Marmot

Does  master / master replication of the SQLIte db.
https://github.com/maxpert/marmot is just golang and NATS Jetstream ( also golang )
it is not dependent fly.io and so can be run on any cloud.

**Comment by poundifdef** [comment]
Just an update - this is working on fly! 

1. Live demo, which is currently running on fly. Does not require any sign-up. https://www.smoothmq.com/demo
2. Here is how you can deploy yourself: https://docs.smoothmq.com/deploy/#flyio
