### ISSUE TITLE
SQS method AmazonSQS.GetQueueUrl not implemented

### ISSUE THREAD

**Issue by jeroendeswaef** [poundifdef/SmoothMQ#17]
When trying an existing application that uses the nodejs `@aws-sdk/client-sqs` library to connect to sqs, I get the following error:

```SQS method AmazonSQS.GetQueueUrl not implemented```

I suppose that is a part of the sqs api that SmoothMQ doesn't implement (yet)?

**Comment by poundifdef** [comment]
Thanks for this! I've just pushed a change to add this method.
