### ISSUE TITLE
Enhance Docker/Kubernetes Compatibility: Consider Moving Database to Subdirectory

### ISSUE THREAD

**Issue by mzehrer** [poundifdef/SmoothMQ#19]
I've been loving the project and I'm looking to deploy it in a Docker/Kubernetes environment. I had a thought that might make this process smoother for others too:

Would it be possible to move the database to a subdirectory within the project structure? This small change could greatly simplify deploying smoothMQ in containerized environments like Docker and Kubernetes.

**Comment by poundifdef** [comment]
Thanks for the suggestion! I've just pushed a change to allow you to configure the file location. Does this help?

https://github.com/poundifdef/SmoothMQ/blob/main/config.yaml#L14-L15

**Comment by mzehrer** [comment]
This looks great. Thank you! Is there a way to override these configurations from the TOML file with environment variables?

**Comment by poundifdef** [comment]
Yep, just added that here https://github.com/poundifdef/SmoothMQ/commit/29908e5cff5c7be40bfb127cd74b719bed8c760b

You can either set the `Q_SQLITE_PATH` env var or specify a `--sqlite-path` argument.

If you run `go run . server --help` then you can see all of the config options along with how to set them via the an argument or an env var.

Thanks for pointing this out!
