### ISSUE TITLE
SQS method AmazonSQS.SendMessageBatch not implemented

### ISSUE THREAD

**Issue by jbs-fm** [poundifdef/smoothmq#21]
Hi there,

Trying out your library it looks really promising thanks.

I'm using this library (https://github.com/bbc/sqs-producer) but can't send messages & get the following error `SQS method AmazonSQS.SendMessageBatch not implemented`.

```
2:59PM WRN zerolog.go:84 > Client error error="UnsupportedOperation: SQS method AmazonSQS.SendMessageBatch not implemented" ip=192.168.214.4 latency="276.969µs" method=POST status=400 url=/
```

Would be grateful if you could add this method.

**Comment by poundifdef** [comment]
Thanks for pointing this out. Agree, will get it added!

**Comment by poundifdef** [comment]
I've just pushed a change that adds the batch insert endpoint. Please send your feedback after testing it out!

Can you tell me more about your setup - are you deploying to k8s, using for testing, what kind of project or stack? This would help me test and develop features that are related to your use case.
