### ISSUE TITLE
Queue names are not case sensitive

### ISSUE THREAD

**Issue by sundbry** [poundifdef/smoothmq#28]
According to the SQS documentation, queue names should be case sensitive. However, during testing it appears they are all converted to lowercase.

[CreateQueue](https://docs.aws.amazon.com/AWSSimpleQueueService/latest/APIReference/API_CreateQueue.html#API_CreateQueue_RequestSyntax)

> [QueueName](https://docs.aws.amazon.com/AWSSimpleQueueService/latest/APIReference/API_CreateQueue.html#API_CreateQueue_RequestSyntax)
>The name of the new queue. The following limits apply to this name:
>A queue name can have up to 80 characters.
>Valid values: alphanumeric characters, hyphens (-), and underscores (_).
>A FIFO queue name must end with the .fifo suffix.
>Queue URLs and names are case-sensitive.

**Comment by poundifdef** [comment]
Makes sense, thanks for flagging.

**Comment by poundifdef** [comment]
Fixed in 7c902df79dfc0bf75a9a41819f3e96e343369d11 and e1fa1b7c511348625eb1f51415f54e5f15a0a3c2
