### ISSUE TITLE
Upgrade 0.2.2 database migrations

### ISSUE THREAD

**Issue by mzehrer** [poundifdef/smoothmq#33]
When updating to 0.2.2 I receive the following error:

[0.428ms] [rows:0] ALTER TABLE `queues` ADD `rate_limit` real NOT NULL
8:07AM FTL sqlite.go:116 > error="Cannot add a NOT NULL column with default value NULL"

**Comment by poundifdef** [comment]
I apologize for this! I made some big changes to the DB schema from version 0.1 to 0.2, including adding an ORM to manage migrations. You may need to re-create your sqlite DB.

**Comment by mzehrer** [comment]
I already did, no worries. I just wanted to point that out.
