### ISSUE TITLE
Web UI returns error "Authorization header is missing"

### ISSUE THREAD

**Issue by yonas** [poundifdef/SmoothMQ#4]
```
❯ xh http://localhost:3001
HTTP/1.1 500 Internal Server Error
Content-Length: 31
Content-Type: text/plain; charset=utf-8
Date: Sun, 30 Jun 2024 17:40:27 GMT

Authorization header is missing
```

**Comment by yonas** [comment]
Do you need a AWS account to use this project?

It looks like you reference amazonaws.com , which shouldn't be needed if this is a complete substitute for AWS SQS.

`	queueUrl := fmt.Sprintf("https://sqs.us-east-1.amazonaws.com/%d/%s", tenantId, req.QueueName)`
-- [protocols/sqs/sqs.go](https://github.com/poundifdef/SmoothMQ/blob/46f8b2266d604cf1a9793338ec7d1a1caad2dc4b/protocols/sqs/sqs.go#L191)

**Comment by poundifdef** [comment]
I should make this more clear! I'll work on updating docs.

The web UI is available via http://localhost:3000

The SQS interface is on http://localhost:3001

You can actually put any hostname for the queue url - I just hardcoded the AWS one for convenience (and you could use your existing aws queue name and things will just work.) You don't need an aws account, but you do need an access/secret key. Right now they are hardcoded to `YOUR_ACCESS_KEY_ID` and `YOUR_SECRET_ACCESS_KEY`.

**Comment by yonas** [comment]
Thanks!

**Comment by poundifdef** [comment]
Just pushed a fix for this. You can now define your own aws access/secret key via a config. Check out: https://github.com/poundifdef/SmoothMQ/blob/main/config.yaml
