### ISSUE TITLE
Marketing tip: Show example monthly prices when hosting this

### ISSUE THREAD

**Issue by caendesilva** [poundifdef/SmoothMQ#5]
Hey! This looks really cool! Here's just a random quick thought I had:

If you were to look up the cheapest hosting solution for this (presumably a VPS?) on various tiers and benchmark the maximum throughputs and concurrencies, that would really help stakeholders compare the pricing of this compared to AWS, which could help corporate adoption.

**Comment by Rauttis** [comment]
The license makes most corporate adoption very unlikely.

**Comment by caendesilva** [comment]
Ah, fair enough! Just wanted to leave my random thought :)

**Comment by poundifdef** [comment]
This is a good suggestion - thank you!
